// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// mode
double mode(NumericVector z);
RcppExport SEXP HW6_mode(SEXP zSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP );
        double __result = mode(z);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// perms
IntegerMatrix perms(double n);
RcppExport SEXP HW6_perms(SEXP nSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< double >::type n(nSEXP );
        IntegerMatrix __result = perms(n);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// shortestpath
int shortestpath(IntegerMatrix G, int x, int y);
RcppExport SEXP HW6_shortestpath(SEXP GSEXP, SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< IntegerMatrix >::type G(GSEXP );
        Rcpp::traits::input_parameter< int >::type x(xSEXP );
        Rcpp::traits::input_parameter< int >::type y(ySEXP );
        int __result = shortestpath(G, x, y);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
