# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Mode Function
#' @description Finds mode of given numeric vector.
#'
#' @param z - a numeric vector.
#' @return Mode - the most frequent number.
#'
#' @export 
mode <- function(z) {
    .Call('HW6_mode', PACKAGE = 'HW6', z)
}

#' @title Perm Function
#' @description Calculates all permutations for an integer vector of given length n.
#'
#' @param n a positive integer.
#' @return P matrix with permutations in rows.
#'
#' @export 
perms <- function(n) {
    .Call('HW6_perms', PACKAGE = 'HW6', n)
}

#' @title Find the length of shortest path.
#' @description Calculates the length of shortest path.
#'
#' @param G an 0-1 adjacency matrix which describes graph.
#' @param x a vertex number from which path should be calculated.
#' @param y a vertex number to which path should be calculated.
#' @return d Length of shortest path between two given vertices.
#'
#' @export
shortestpath <- function(G, x, y) {
    .Call('HW6_shortestpath', PACKAGE = 'HW6', G, x, y)
}

